spring:
  application:
    name: authentication-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 50MB
springdoc:
  default-produces-media-type: application/json
server:
  port: 8088