services:
  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - microservices-net
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - microservices-net
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "22181:2181"
    networks:
      - microservices-net
  kafka:
    image: confluentinc/cp-kafka:6.2.1
    container_name: ms_kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    networks:
      - microservices-net
      
  # Configuration server - must start first for other services
  config-server:
    image: windlogs/config-server:${BUILD_NUMBER}
    container_name: config-server
    ports:
      - "8888:8888"
    networks:
      - microservices-net
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      
  # Discovery server - starts after config server
  discovery:
    image: windlogs/discovery:${BUILD_NUMBER}
    container_name: discovery
    ports:
      - "8761:8761"
    networks:
      - microservices-net
    depends_on:
      - config-server
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      
  # Authentication service
  authentication:
    image: windlogs/authentication:${BUILD_NUMBER}
    container_name: authentication
    ports:
      - "8088:8088"
    networks:
      - microservices-net
    depends_on:
      - config-server
      - discovery
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      
  # Gateway service
  gateway:
    image: windlogs/gateway:${BUILD_NUMBER}
    container_name: gateway
    ports:
      - "8222:8222"
    networks:
      - microservices-net
    depends_on:
      - config-server
      - discovery
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      
  # Notification service
  notification:
    image: windlogs/notification:${BUILD_NUMBER}
    container_name: notification
    ports:
      - "8084:8084"
    networks:
      - microservices-net
    depends_on:
      - config-server
      - discovery
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
      
  # Tickets service
  tickets:
    image: windlogs/tickets:${BUILD_NUMBER}
    container_name: tickets
    ports:
      - "8083:8083"
    networks:
      - microservices-net
    depends_on:
      - config-server
      - discovery
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_CLOUD_CONFIG_URI=http://config-server:8888
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://discovery:8761/eureka/
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9092

networks:
  microservices-net:
    driver: bridge

