spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service-auth
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
        - id: authentication-service-employees
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/v1/employees
        - id: authentication-service-users
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/users/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/v1/users
        - id: authentication-service-users
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/admin/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/v1/admin
        - id: authentication-service-partner
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/projects/**
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/(?<segment>.*), /$\{segment}
            - AddRequestHeader=X-Forwarded-Prefix, /api/v1/projects
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "${FRONTEND_URL:http://localhost:4200}"  # Externalize the URL
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Authorization
              - Content-Type
              - X-Requested-With
              - Accept
              - Origin
              - Access-Control-Request-Method
              - Access-Control-Request-Headers
            maxAge: 3600  # Cache preflight requests for 1 hour
            allowCredentials: true
            exposedHeaders:
              - Authorization
  web:
    resources:
      static-locations: classpath:/static/,file:./public/

server:
  port: 8222


