spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/api/v1/auth/**
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
              - Path=/api/v1/employees/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "${FRONTEND_URL:http://localhost:4200}"  # Externalize the URL
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            maxAge: 3600  # Cache preflight requests for 1 hour
            allowCredentials: true
server:
  port: 8222

